# Generated by Django 3.2.11 on 2022-01-23 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_menu_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_type', to='core.componenttype')),
                ('core_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_page', to='core.corepage')),
            ],
        ),
    ]
