# Generated by Django 3.2.11 on 2022-01-23 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_componenttype_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corepage',
            name='menu_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='core.menu'),
        ),
    ]
