# Generated by Django 3.2.11 on 2022-01-23 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_corepage_menu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='core_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='core.corepage'),
        ),
    ]
