# Generated by Django 5.2.6 on 2025-09-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_section_foreign_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="media_file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
