# Generated by Django 3.2.11 on 2022-01-23 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_section_core_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='core_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_page', to='core.corepage'),
        ),
    ]
