# Generated by Django 3.2.11 on 2022-01-23 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_section_core_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componenttype',
            name='component_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='corepage',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_type', to='core.componenttype', to_field='component_name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='core_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_page', to='core.corepage', to_field='title'),
        ),
    ]
