# Generated by Django 3.2.11 on 2022-01-26 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220123_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corepage',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='core.menu'),
        ),
    ]
