# Generated by Django 3.2.11 on 2022-01-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_corepage_menu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='on_footer',
            field=models.BooleanField(default=False),
        ),
    ]
