# Generated by Django 3.2.11 on 2022-01-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_menu_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='TileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('descprotion', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('position', models.IntegerField()),
                ('on_landing', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('core_page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_core_page', to='core.corepage')),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('descprotion', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('position', models.IntegerField()),
                ('on_landing', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('core_page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_core_page', to='core.corepage')),
            ],
            options={
                'verbose_name_plural': 'Media',
            },
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('descprotion', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('position', models.IntegerField()),
                ('on_landing', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('core_page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_core_page', to='core.corepage')),
            ],
            options={
                'verbose_name_plural': 'Latest News',
            },
        ),
        migrations.CreateModel(
            name='KnowAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('descprotion', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('position', models.IntegerField()),
                ('on_landing', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('core_page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='know_us_core_page', to='core.corepage')),
            ],
            options={
                'verbose_name_plural': 'Know About Us',
            },
        ),
        migrations.CreateModel(
            name='Glance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('position', models.IntegerField()),
                ('core_page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glance_core_page', to='core.corepage')),
            ],
            options={
                'verbose_name_plural': 'Glance',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('descprotion', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('position', models.IntegerField()),
                ('on_landing', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('core_page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_core_page', to='core.corepage')),
            ],
            options={
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='CardMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('descprotion', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('position', models.IntegerField()),
                ('on_landing', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('core_page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_core_page', to='core.corepage')),
            ],
            options={
                'verbose_name_plural': 'Card Menu',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('descprotion', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('position', models.IntegerField()),
                ('on_landing', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('core_page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_core_page', to='core.corepage')),
            ],
            options={
                'verbose_name_plural': 'Announcement',
            },
        ),
    ]
