# Generated by Django 3.2.11 on 2022-01-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_menu_link'),
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='media',
            new_name='MediaFile',
        ),
    ]
