# Generated by Django 3.2.11 on 2022-01-23 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_componenttype_section'),
        ('component', '0002_rename_media_mediafile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TileType',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='descprotion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='cardmenu',
            old_name='descprotion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='descprotion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='knowaboutus',
            old_name='descprotion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='latestnews',
            old_name='descprotion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='mediafile',
            old_name='descprotion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='descprotion',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='glance',
            name='position',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='core_page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_section', to='core.section'),
        ),
        migrations.AlterField(
            model_name='cardmenu',
            name='core_page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_section', to='core.section'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='core_page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_section', to='core.section'),
        ),
        migrations.AlterField(
            model_name='glance',
            name='core_page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glance_section', to='core.section'),
        ),
        migrations.AlterField(
            model_name='knowaboutus',
            name='core_page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='know_section', to='core.section'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='core_page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_section', to='core.section'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='core_page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_section', to='core.section'),
        ),
        migrations.AlterField(
            model_name='product',
            name='core_page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_section', to='core.section'),
        ),
    ]
