# Generated by Django 3.2.11 on 2022-01-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0003_auto_20220123_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='core_page_id',
            new_name='section_id',
        ),
        migrations.RenameField(
            model_name='cardmenu',
            old_name='core_page_id',
            new_name='section_id',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='core_page_id',
            new_name='section_id',
        ),
        migrations.RenameField(
            model_name='glance',
            old_name='core_page_id',
            new_name='section_id',
        ),
        migrations.RenameField(
            model_name='knowaboutus',
            old_name='core_page_id',
            new_name='section_id',
        ),
        migrations.RenameField(
            model_name='latestnews',
            old_name='core_page_id',
            new_name='section_id',
        ),
        migrations.RenameField(
            model_name='mediafile',
            old_name='core_page_id',
            new_name='section_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='core_page_id',
            new_name='section_id',
        ),
    ]
