# Generated by Django 3.2.11 on 2022-02-01 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_menu_on_footer'),
        ('component', '0004_auto_20220123_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('position', models.IntegerField()),
                ('on_landing', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_data', to='core.section')),
            ],
            options={
                'verbose_name_plural': 'Component Data',
            },
        ),
    ]
