# Generated by Django 3.2.11 on 2022-05-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='icon_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='footer_icon',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='footer_sub_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='icon',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='sub_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
